import streamlit.components.v1 as components

# Parse duration slider correctly into seconds
duration_map = {"30 sec": 30.0, "1 min": 60.0, "2 min": 120.0, "3 min": 180.0}
selected_duration_sec = duration_map.get(duration_label, 30.0)

if generate:
    if not lyrics.strip():
        st.warning("Please paste lyrics or generate free lyrics first.")
        st.stop()

    status = st.empty()
    status.info(f"🎼 Generating {duration_label} song with dynamic variation...")
    
    provider = LocalFallbackProvider()
    # Pass the selected duration into the generator
    audio, label = provider.generate(lyrics, style_prompt=STYLES[style], seed=random.randint(1, 100000), duration_sec=selected_duration_sec)
    
    if validate_audio(audio):
        st.session_state["audio"] = bytes(audio)
        st.session_state["title"] = title.strip() or "RacharlaMusic Song"
        st.session_state["provider"] = label
        st.session_state["lyrics_to_sing"] = lyrics
        st.session_state["language"] = language
        status.success(f"🎉 Song generated successfully ({duration_label})!")
    else:
        status.error("Generation failed.")

if "audio" in st.session_state and validate_audio(st.session_state["audio"]):
    st.markdown('<div class="glass">', unsafe_allow_html=True)
    st.markdown("## 🎉 Your song is ready")
    st.caption(f"Generated by **{st.session_state.get('provider', 'Synthesizer')}** ({duration_label})")
    
    # Standard Audio Player for Music
    st.audio(st.session_state["audio"], format="audio/wav")
    
    # Built-in Browser Vocal Singer (Sings lyrics concurrently in Telugu/English)
    st.markdown("### 🎤 Vocal Singing Companion")
    st.caption("Click below to sing your lyrics along with the music track:")
    
    clean_lyrics_js = st.session_state.get("lyrics_to_sing", "").replace("\n", "\\n").replace('"', '\\"')
    lang_code = "te-IN" if "Telugu" in st.session_state.get("language", "Telugu") else "en-US"
    
    sing_html = f"""
    <div style="background: rgba(255,255,255,0.05); padding: 15px; border-radius: 14px; border: 1px solid rgba(255,255,255,0.1);">
        <button onclick="singLyrics()" style="background: linear-gradient(90deg,#ff18c9,#824eff,#00cef4); color: white; border: none; padding: 12px 24px; border-radius: 12px; font-weight: bold; cursor: pointer; font-size: 1rem;">▶️ Start Vocal Singing</button>
        <button onclick="stopSinging()" style="background: rgba(255,255,255,0.1); color: white; border: none; padding: 12px 24px; border-radius: 12px; font-weight: bold; cursor: pointer; font-size: 1rem; margin-left: 10px;">⏹️ Stop Vocals</button>
        <p id="sing-status" style="margin-top: 10px; color: #00cef4; font-size: 0.9rem;"></p>
    </div>
    <script>
    let utter = null;
    function singLyrics() {{
        window.speechSynthesis.cancel();
        const text = "{clean_lyrics_js}";
        utter = new SpeechSynthesisUtterance(text);
        utter.lang = "{lang_code}";
        utter.rate = 0.9; // Natural singing pace
        utter.pitch = 1.0;
        
        utter.onstart = function() {{
            document.getElementById('sing-status').innerText = "🎤 Vocals active: Singing lyrics...";
        }};
        utter.onend = function() {{
            document.getElementById('sing-status').innerText = "✓ Vocal performance finished.";
        }};
        window.speechSynthesis.speak(utter);
    }}
    function stopSinging() {{
        window.speechSynthesis.cancel();
        document.getElementById('sing-status').innerText = "Vocals stopped.";
    }}
    </script>
    """
    components.html(sing_html, height=130)

    fname = re.sub(r"[^A-Za-z0-9_-]+", "_", st.session_state.get("title", "Song"))
    st.download_button("⬇️ DOWNLOAD AUDIO", data=st.session_state["audio"], file_name=f"{fname}.wav", mime="audio/wav", use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)
